### complex

In [5]:
import numpy as np

Nx = 4
Ny = 5

A = np.random.rand(Nx, Ny) + 1j*np.random.rand(Nx, Ny)

print(A)

np.savetxt("other/A.csv", A, delimiter=",", fmt=["%.10e%+.10ei"]*Ny)



[[ 0.50123352+0.38108705j  0.33606717+0.62888016j  0.01554074+0.38035886j
   0.02416282+0.38643934j  0.52947205+0.65266263j]
 [ 0.19754254+0.82001439j  0.34739202+0.44001965j  0.06952325+0.97247766j
   0.66127508+0.96051018j  0.40411675+0.70158918j]
 [ 0.33624054+0.59000855j  0.66374923+0.18739737j  0.30603571+0.96451422j
   0.61024132+0.78209921j  0.97323197+0.47453836j]
 [ 0.78609869+0.96336566j  0.32538834+0.86985288j  0.33730678+0.90368692j
   0.53904859+0.2750846j   0.77439195+0.20613686j]]


### float

In [17]:
import numpy as np

Nx = 4
Ny = 5

A = np.random.rand(Nx, Ny)

print(A)

np.savetxt("other/A.csv", A, delimiter=",", fmt=["%.10e"]*Ny)



[[ 0.79449283  0.79753861  0.99422327  0.32302459  0.64355714]
 [ 0.96528746  0.40707261  0.34726173  0.01354714  0.10935655]
 [ 0.9965893   0.29748386  0.62055114  0.70779699  0.59053801]
 [ 0.90654365  0.14789584  0.45017441  0.4986661   0.69480938]]


### append

In [20]:
import numpy as np

Nx = 4
Ny = 5

f = open('other/A.csv','ab')

for i in range(2):
    A = np.random.rand(Nx, Ny)
    print(A)
    np.savetxt(f, A, delimiter=",", fmt=["%.10e"]*Ny)

f.close()


[[ 0.92215095  0.78169847  0.8792918   0.30501292  0.77689167]
 [ 0.37541911  0.49735735  0.66392947  0.5561751   0.011629  ]
 [ 0.38659188  0.33537839  0.67976282  0.92101696  0.21261026]
 [ 0.91766792  0.07208997  0.43641533  0.63973342  0.28542898]]
[[ 0.80392468  0.17643853  0.01133508  0.77314856  0.45268345]
 [ 0.73035236  0.91794498  0.56454891  0.52529852  0.83006657]
 [ 0.64979941  0.12669817  0.64721517  0.15235392  0.39099388]
 [ 0.56541136  0.44510304  0.1684274   0.1315902   0.15248326]]


### load

In [21]:

A = np.loadtxt("other/A.csv",delimiter=',')
#A = np.genfromtxt("other/A.csv",delimiter=',')

print(A)


[[ 0.79449283  0.79753861  0.99422327  0.32302459  0.64355714]
 [ 0.96528746  0.40707261  0.34726173  0.01354714  0.10935655]
 [ 0.9965893   0.29748386  0.62055114  0.70779699  0.59053801]
 [ 0.90654365  0.14789584  0.45017441  0.4986661   0.69480938]
 [ 0.92215095  0.78169847  0.8792918   0.30501292  0.77689167]
 [ 0.37541911  0.49735735  0.66392947  0.5561751   0.011629  ]
 [ 0.38659188  0.33537839  0.67976282  0.92101696  0.21261026]
 [ 0.91766792  0.07208997  0.43641533  0.63973342  0.28542898]
 [ 0.80392468  0.17643853  0.01133508  0.77314856  0.45268345]
 [ 0.73035236  0.91794498  0.56454891  0.52529852  0.83006657]
 [ 0.64979941  0.12669817  0.64721517  0.15235392  0.39099388]
 [ 0.56541136  0.44510304  0.1684274   0.1315902   0.15248326]]
